name: Docker Image CI

on:
  push:
    branshs: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pakages: write

    steps:
    - uses: actions/checkout@v3
    - name: Login to repository
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ screts.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/express-docker:$(date +%s)